[2024-06-11 22:51:02,731] torch.distributed.run: [WARNING] 
[2024-06-11 22:51:02,731] torch.distributed.run: [WARNING] *****************************************
[2024-06-11 22:51:02,731] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-06-11 22:51:02,731] torch.distributed.run: [WARNING] *****************************************
/vast/home/ajherman/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/vast/home/ajherman/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/vast/home/ajherman/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/vast/home/ajherman/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
Config:
 GPT2Config {
  "_name_or_path": "gpt2",
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.41.2",
  "use_cache": true,
  "vocab_size": 50257
}

Number of model parameters: 124439808
Config:
 GPT2Config {
  "_name_or_path": "gpt2",
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.41.2",
  "use_cache": true,
  "vocab_size": 50257
}

Number of model parameters: 124439808
Config:
 GPT2Config {
  "_name_or_path": "gpt2",
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.41.2",
  "use_cache": true,
  "vocab_size": 50257
}

Number of model parameters: 124439808
Config:
 GPT2Config {
  "_name_or_path": "gpt2",
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.41.2",
  "use_cache": true,
  "vocab_size": 50257
}

Number of model parameters: 124439808
Dataset info for monology/pile-uncopyrighted is not completely ready yet.
Dataset info for monology/pile-uncopyrighted is not completely ready yet.
Dataset info for monology/pile-uncopyrighted is not completely ready yet.
Dataset info for monology/pile-uncopyrighted is not completely ready yet.
No config specified, defaulting to the single config: pile-uncopyrighted/default
Using custom data configuration default-block_size=655360
Loading Dataset Infos from /vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/packaged_modules/json
The JSON loader parameter `block_size` is deprecated. Please use `chunksize` instead
No config specified, defaulting to the single config: pile-uncopyrighted/default
Using custom data configuration default-block_size=655360
Loading Dataset Infos from /vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/packaged_modules/json
The JSON loader parameter `block_size` is deprecated. Please use `chunksize` instead
No config specified, defaulting to the single config: pile-uncopyrighted/default
Using custom data configuration default-block_size=655360
Loading Dataset Infos from /vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/packaged_modules/json
The JSON loader parameter `block_size` is deprecated. Please use `chunksize` instead
No config specified, defaulting to the single config: pile-uncopyrighted/default
Using custom data configuration default-block_size=655360
Loading Dataset Infos from /vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/packaged_modules/json
The JSON loader parameter `block_size` is deprecated. Please use `chunksize` instead
No dataset info for wikitext available (HTTPError: 500 Server Error: Internal Server Error for url: https://datasets-server.huggingface.co/info?dataset=wikitext)
No dataset info for wikitext available (HTTPError: 500 Server Error: Internal Server Error for url: https://datasets-server.huggingface.co/info?dataset=wikitext)
No dataset info for wikitext available (HTTPError: 500 Server Error: Internal Server Error for url: https://datasets-server.huggingface.co/info?dataset=wikitext)
No dataset info for wikitext available (HTTPError: 500 Server Error: Internal Server Error for url: https://datasets-server.huggingface.co/info?dataset=wikitext)
Exception occurred: BuilderConfig ParquetConfig(name='wikitext-2-raw-v1', version=0.0.0, data_dir=None, data_files={'test': ['wikitext-2-raw-v1/test-*'], 'train': ['wikitext-2-raw-v1/train-*'], 'validation': ['wikitext-2-raw-v1/validation-*']}, description=None, batch_size=None, columns=None, features=None) doesn't have a 'block_size' key.
Traceback (most recent call last):
  File "/vast/home/ajherman/transformers/ari/gpt2_train.py", line 90, in <module>
    eval_dataset = load_dataset('wikitext', 'wikitext-2-raw-v1', split='validation',block_size=655360)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/load.py", line 2592, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/load.py", line 2301, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/builder.py", line 374, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/builder.py", line 620, in _create_builder_config
    raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
ValueError: BuilderConfig ParquetConfig(name='wikitext-2-raw-v1', version=0.0.0, data_dir=None, data_files={'test': ['wikitext-2-raw-v1/test-*'], 'train': ['wikitext-2-raw-v1/train-*'], 'validation': ['wikitext-2-raw-v1/validation-*']}, description=None, batch_size=None, columns=None, features=None) doesn't have a 'block_size' key.
Exception occurred: BuilderConfig ParquetConfig(name='wikitext-2-raw-v1', version=0.0.0, data_dir=None, data_files={'test': ['wikitext-2-raw-v1/test-*'], 'train': ['wikitext-2-raw-v1/train-*'], 'validation': ['wikitext-2-raw-v1/validation-*']}, description=None, batch_size=None, columns=None, features=None) doesn't have a 'block_size' key.
Traceback (most recent call last):
  File "/vast/home/ajherman/transformers/ari/gpt2_train.py", line 90, in <module>
    eval_dataset = load_dataset('wikitext', 'wikitext-2-raw-v1', split='validation',block_size=655360)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/load.py", line 2592, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/load.py", line 2301, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/builder.py", line 374, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/builder.py", line 620, in _create_builder_config
    raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
ValueError: BuilderConfig ParquetConfig(name='wikitext-2-raw-v1', version=0.0.0, data_dir=None, data_files={'test': ['wikitext-2-raw-v1/test-*'], 'train': ['wikitext-2-raw-v1/train-*'], 'validation': ['wikitext-2-raw-v1/validation-*']}, description=None, batch_size=None, columns=None, features=None) doesn't have a 'block_size' key.
Exception occurred: BuilderConfig ParquetConfig(name='wikitext-2-raw-v1', version=0.0.0, data_dir=None, data_files={'test': ['wikitext-2-raw-v1/test-*'], 'train': ['wikitext-2-raw-v1/train-*'], 'validation': ['wikitext-2-raw-v1/validation-*']}, description=None, batch_size=None, columns=None, features=None) doesn't have a 'block_size' key.
Traceback (most recent call last):
  File "/vast/home/ajherman/transformers/ari/gpt2_train.py", line 90, in <module>
    eval_dataset = load_dataset('wikitext', 'wikitext-2-raw-v1', split='validation',block_size=655360)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/load.py", line 2592, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/load.py", line 2301, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/builder.py", line 374, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/builder.py", line 620, in _create_builder_config
    raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
ValueError: BuilderConfig ParquetConfig(name='wikitext-2-raw-v1', version=0.0.0, data_dir=None, data_files={'test': ['wikitext-2-raw-v1/test-*'], 'train': ['wikitext-2-raw-v1/train-*'], 'validation': ['wikitext-2-raw-v1/validation-*']}, description=None, batch_size=None, columns=None, features=None) doesn't have a 'block_size' key.
Exception occurred: BuilderConfig ParquetConfig(name='wikitext-2-raw-v1', version=0.0.0, data_dir=None, data_files={'test': ['wikitext-2-raw-v1/test-*'], 'train': ['wikitext-2-raw-v1/train-*'], 'validation': ['wikitext-2-raw-v1/validation-*']}, description=None, batch_size=None, columns=None, features=None) doesn't have a 'block_size' key.
Traceback (most recent call last):
  File "/vast/home/ajherman/transformers/ari/gpt2_train.py", line 90, in <module>
    eval_dataset = load_dataset('wikitext', 'wikitext-2-raw-v1', split='validation',block_size=655360)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/load.py", line 2592, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/load.py", line 2301, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/builder.py", line 374, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/.local/lib/python3.11/site-packages/datasets/builder.py", line 620, in _create_builder_config
    raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
ValueError: BuilderConfig ParquetConfig(name='wikitext-2-raw-v1', version=0.0.0, data_dir=None, data_files={'test': ['wikitext-2-raw-v1/test-*'], 'train': ['wikitext-2-raw-v1/train-*'], 'validation': ['wikitext-2-raw-v1/validation-*']}, description=None, batch_size=None, columns=None, features=None) doesn't have a 'block_size' key.
